const BREAKPOINT_XS = 0
const BREAKPOINT_SM = 600
const BREAKPOINT_MD = 1024
const BREAKPOINT_LG = 1440
const BREAKPOINT_XL = 1920

export {
  BREAKPOINT_XS,
  BREAKPOINT_SM,
  BREAKPOINT_MD,
  BREAKPOINT_LG,
  BREAKPOINT_XL
}
