const OPEN_SANS = 'Open Sans'
const COMFORTAA = 'Comfortaa'
const NUNITO = 'Nunito'

const LIGHT_WEIGHT = 300
const REGULAR_WEIGHT = 400
const MEDIUM_WEIGHT = 500
const SEMI_BOLD_WEIGHT = 600
const BOLD_WEIGHT = 700
const EXTRA_BOLD_WEIGHT = 800

export {
  OPEN_SANS,
  COMFORTAA,
  NUNITO,
  LIGHT_WEIGHT,
  REGULAR_WEIGHT,
  MEDIUM_WEIGHT,
  SEMI_BOLD_WEIGHT,
  BOLD_WEIGHT,
  EXTRA_BOLD_WEIGHT
}
