import {
  BOLD_WEIGHT,
  COMFORTAA,
  EXTRA_BOLD_WEIGHT,
  LIGHT_WEIGHT,
  MEDIUM_WEIGHT,
  NUNITO,
  OPEN_SANS,
  REGULAR_WEIGHT,
  SEMI_BOLD_WEIGHT
} from './config'

const OPEN_SANS_LIGHT = {
  font: OPEN_SANS,
  weight: LIGHT_WEIGHT
}

const OPEN_SANS_REGULAR = {
  font: OPEN_SANS,
  weight: REGULAR_WEIGHT
}

const OPEN_SANS_SEMI_BOLD = {
  font: OPEN_SANS,
  weight: SEMI_BOLD_WEIGHT
}

const OPEN_SANS_BOLD = {
  font: OPEN_SANS,
  weight: BOLD_WEIGHT
}

const OPEN_SANS_EXTRA_BOLD = {
  font: OPEN_SANS,
  weight: EXTRA_BOLD_WEIGHT
}

const COMFORTAA_LIGHT = {
  font: COMFORTAA,
  weight: LIGHT_WEIGHT
}

const COMFORTAA_REGULAR = {
  font: COMFORTAA,
  weight: REGULAR_WEIGHT
}

const COMFORTAA_MEDIUM = {
  font: COMFORTAA,
  weight: MEDIUM_WEIGHT
}

const COMFORTAA_SEMI_BOLD = {
  font: COMFORTAA,
  weight: SEMI_BOLD_WEIGHT
}

const COMFORTAA_BOLD = {
  font: COMFORTAA,
  weight: BOLD_WEIGHT
}

const COMFORTAA_EXTRA_BOLD = {
  font: COMFORTAA,
  weight: EXTRA_BOLD_WEIGHT
}

const NUNITO_LIGHT = {
  font: NUNITO,
  weight: LIGHT_WEIGHT
}

const NUNITO_REGULAR = {
  font: NUNITO,
  weight: REGULAR_WEIGHT
}

const NUNITO_MEDIUM = {
  font: NUNITO,
  weight: MEDIUM_WEIGHT
}

const NUNITO_SEMI_BOLD = {
  font: NUNITO,
  weight: SEMI_BOLD_WEIGHT
}

const NUNITO_BOLD = {
  font: NUNITO,
  weight: BOLD_WEIGHT
}

const NUNITO_EXTRA_BOLD = {
  font: NUNITO,
  weight: EXTRA_BOLD_WEIGHT
}

export {
  OPEN_SANS_LIGHT,
  OPEN_SANS_REGULAR,
  OPEN_SANS_SEMI_BOLD,
  OPEN_SANS_BOLD,
  OPEN_SANS_EXTRA_BOLD,
  COMFORTAA_LIGHT,
  COMFORTAA_REGULAR,
  COMFORTAA_MEDIUM,
  COMFORTAA_SEMI_BOLD,
  COMFORTAA_BOLD,
  COMFORTAA_EXTRA_BOLD,
  NUNITO_LIGHT,
  NUNITO_REGULAR,
  NUNITO_MEDIUM,
  NUNITO_SEMI_BOLD,
  NUNITO_BOLD,
  NUNITO_EXTRA_BOLD
}
