import * as BREAKPOINTS_CONFIG from '../breakpoints'

const BREAKPOINTS = {
  breakpoints: {
    values: {
      lg: BREAKPOINTS_CONFIG.BREAKPOINT_LG,
      md: BREAKPOINTS_CONFIG.BREAKPOINT_MD,
      sm: BREAKPOINTS_CONFIG.BREAKPOINT_SM,
      xs: BREAKPOINTS_CONFIG.BREAKPOINT_XS,
      xl: BREAKPOINTS_CONFIG.BREAKPOINT_XL
    }
  }
}

export { BREAKPOINTS }
