const YELLOW_DARKER = '#FCC812'
const YELLOW_DARK = '#FDD341'
const YELLOW_MEDIUM = '#FDDE71'
const YELLOW_LIGHT = '#FEE9A0'
const YELLOW_LIGHTER = '#FEF4D0'

const GREEN_DARKER = '#567343'
const GREEN_DARK = '#788F69'
const GREEN_MEDIUM = '#9AAB8E'
const GREEN_LIGHT = '#BBC7B4'
const GREEN_LIGHTER = '#DDE3D9'

const PINK_DARKER = '#FCA1A9'
const PINK_DARK = '#FDB4BA'
const PINK_MEDIUM = '#FDC7CB'
const PINK_LIGHT = '#FED9DD'
const PINK_LIGHTER = '#FEECEE'

const BLACK_DARKER = '#000000'
const BLACK_DARK = '#333333'
const BLACK_MEDIUM = '#666666'
const BLACK_LIGHT = '#999999'
const BLACK_LIGHTER = '#CCCCCC'

const GREEN_SUCCESS_DARKER = '#13BA24'
const GREEN_SUCCESS_DARK = '#42C850'
const GREEN_SUCCESS_MEDIUM = '#72D67C'
const GREEN_SUCCESS_LIGHT = '#A1E3A7'
const GREEN_SUCCESS_LIGHTER = '#D0F1D3'

const SAPPHIRINE_DARKER = '#100174'
const SAPPHIRINE_DARK = '#403490'
const SAPPHIRINE_MEDIUM = '#7067AC'
const SAPPHIRINE_LIGHT = '#9F99C7'
const SAPPHIRINE_LIGHTER = '#CFCCE3'

const TURQUOISE_DARKER = '#77CEBC'
const TURQUOISE_DARK = '#92D8C9'
const TURQUOISE_MEDIUM = '#ADE2D7'
const TURQUOISE_LIGHT = '#C9EBE4'
const TURQUOISE_LIGHTER = '#E4F5F2'

const PEACH_DARKER = '#FEEEE1'
const PEACH_DARK = '#FEF1E7'
const PEACH_MEDIUM = '#FEF5ED'
const PEACH_LIGHT = '#FFF8F3'
const PEACH_LIGHTER = '#FFFCF9'

const GRAY_DARKER = '#D9D9D9'
const GRAY_DARK = '#E1E1E1'
const GRAY_MEDIUM = '#E8E8E8'
const GRAY_LIGHT = '#F0F0F0'
const GRAY_LIGHTER = '#F7F7F7'

const RED_DARKER = '#D21C1C'
const RED_DARK = '#DB4949'
const RED_MEDIUM = '#E47777'
const RED_LIGHT = '#EDA4A4'
const RED_LIGHTER = '#F6D2D2'

const PURPLE_DARKER = '#5D5FEF'
const PURPLE_DARK = '#7D7FF2'
const PURPLE_MEDIUM = '#9E9FF5'
const PURPLE_LIGHT = '#BEBFF9'
const PURPLE_LIGHTER = '#DFDFFC'

const BLUE_DARKER = '#5DA9EF'
const BLUE_DARK = '#7DBAF2'
const BLUE_MEDIUM = '#9ECBF5'
const BLUE_LIGHT = '#BEDDF9'
const BLUE_LIGHTER = '#DFEEFC'

const OTHER_BLUE = '#94B7BD'
const OTHER_RED = '#FD6769'
const OTHER_LIGHT_PINK = '#FED9DB'
const OTHER_GREY_LIGHT = '#64748B'

const BACKGROUND = '#FFFFFF'

export {
  YELLOW_DARKER,
  YELLOW_DARK,
  YELLOW_MEDIUM,
  YELLOW_LIGHT,
  YELLOW_LIGHTER,
  GREEN_DARKER,
  GREEN_DARK,
  GREEN_MEDIUM,
  GREEN_LIGHT,
  GREEN_LIGHTER,
  PINK_DARK,
  PINK_DARKER,
  PINK_MEDIUM,
  PINK_LIGHT,
  PINK_LIGHTER,
  BLACK_DARKER,
  BLACK_DARK,
  BLACK_MEDIUM,
  BLACK_LIGHT,
  BLACK_LIGHTER,
  GREEN_SUCCESS_DARKER,
  GREEN_SUCCESS_DARK,
  GREEN_SUCCESS_MEDIUM,
  GREEN_SUCCESS_LIGHT,
  GREEN_SUCCESS_LIGHTER,
  SAPPHIRINE_DARKER,
  SAPPHIRINE_DARK,
  SAPPHIRINE_MEDIUM,
  SAPPHIRINE_LIGHT,
  SAPPHIRINE_LIGHTER,
  TURQUOISE_DARKER,
  TURQUOISE_DARK,
  TURQUOISE_MEDIUM,
  TURQUOISE_LIGHT,
  TURQUOISE_LIGHTER,
  PEACH_DARKER,
  PEACH_DARK,
  PEACH_MEDIUM,
  PEACH_LIGHT,
  PEACH_LIGHTER,
  GRAY_DARKER,
  GRAY_DARK,
  GRAY_MEDIUM,
  GRAY_LIGHT,
  GRAY_LIGHTER,
  RED_DARKER,
  RED_DARK,
  RED_MEDIUM,
  RED_LIGHT,
  RED_LIGHTER,
  PURPLE_DARKER,
  PURPLE_DARK,
  PURPLE_MEDIUM,
  PURPLE_LIGHT,
  PURPLE_LIGHTER,
  BLUE_DARKER,
  BLUE_DARK,
  BLUE_MEDIUM,
  BLUE_LIGHT,
  BLUE_LIGHTER,
  OTHER_BLUE,
  OTHER_RED,
  OTHER_LIGHT_PINK,
  OTHER_GREY_LIGHT,
  BACKGROUND
}
